routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [App\Http\Controllers\WelcomeController::class, 'index'])->name('welcome.index');

Route::get('city/{department}', [App\Http\Controllers\CityController::class, 'getCities'])->name('city.index');
Route::post('competitor/create', [App\Http\Controllers\CompetitorController::class, 'store'])->name('competitor.add');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/logout',  [App\Http\Controllers\Auth\LoginController::class, 'logout']);

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;

    
      /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'department_id',
    ];

    public function department()
    {
        return $this->belongsTo('App\Models\Department', 'department_id');
    }
}

app/Models/Competitor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Competitor extends Model
{
    use HasFactory;

      /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'document_type',
        'document_number',
        'city_id',
        'phone',
        'email',
    ];

    public function city()
    {    
        return $this->belongsTo('App\Models\City', 'city_id');
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }
}

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;

     /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
    ];

    public function cities()
    {
        return $this->belongsToMany('App\Models\City');
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
    ];


    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\City;
use App\Models\Department;

class CityController extends Controller
{

    public function getCities(Department $department)
    {
     
       $cities = City::where('department_id',$department->id)->get();
       return $cities;

    }
}

app/Http/Controllers/CompetitorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Competitor;
use Illuminate\Http\Request;

class CompetitorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'first_name' => 'required|min:3',
            'last_name' => 'required|min:3',
            'document_type' => 'required',
            'document_number' => 'numeric|min:8|required|unique:competitors',
            'city' => 'required',
            'phone_number' => 'numeric|required|min:10',
            'email' => 'unique:competitors'
        ];
        $request->validate($rules);
        
        Competitor::create([
            'first_name' => $request->input('first_name'),
            'last_name' => $request->input('last_name'),
            'document_type' => $request->input('document_type'),
            'document_number' => $request->input('document_number'),
            'city_id' => $request->input('city'),
            'phone' => $request->input('phone_number'),
            'email' => $request->input('email'),
        ]);

        //Verificamos si hay ganadores

        $competitors = Competitor::all();

        if($competitors->count()===5){
            // Buscamos uno al azar
            $competitor = Competitor::orderByRaw("RAND()")->limit(1)->first();
            $competitor->status = 'Winner';
            $competitor->save();
        }

        return back()->with([
            'flash_message' => '¡Registro exitoso!',
            'flash_message_important' => true,
            'flash_alert_type' => "success",
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Competitor  $competitor
     * @return \Illuminate\Http\Response
     */
    public function show(Competitor $competitor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Competitor  $competitor
     * @return \Illuminate\Http\Response
     */
    public function edit(Competitor $competitor)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Competitor  $competitor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Competitor $competitor)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Competitor  $competitor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Competitor $competitor)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Competitor;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $competitors = Competitor::all();
        return view('home', compact('competitors'));
    }
}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Competitor;
use App\Models\Department;

class WelcomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       //consultamos si hay ganadores
       $winner = Competitor::where('status','Winner')->first();

       //consultamos los departamentos

       $departments = Department::orderBy('name', 'ASC')->get();

       if($winner){
            return view('welcome',compact('winner'));
       }else{
            return view('welcome', compact('departments'));
       }

       
    }
}

resources/views/home.blade.php
@extends('layouts.app')
@push('styles')
    <link rel="stylesheet" href="{{ asset('css/home.css') }}">
@endpush

@section('content')
<div class="container">
    <div class="row justify-content-center table-container">
        <div class="col-12">
            <table  id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th width="15%">Competidor</th>
                        <th width="10%">Tipo de documento</th>
                        <th width="10%">Número de documento</th>
                        <th width="10%" >Departamento</th>
                        <th width="10%" >Ciudad</th>
                        <th width="10%" >Celular</th>
                        <th width="10%">Correo</th>
                        <th width="15%">Fecha de Registro</th>
                        <th width="10%">Estado</th>
                    </tr>
                </thead>
                <tbody>
                   @foreach($competitors as $competitor)
                   <tr>
                       <td>{{$competitor->full_name}}</td>
                       <td>{{$competitor->document_type}}</td>
                       <td>{{$competitor->document_number}}</td>
                       <td>{{$competitor->city->department->name}}</td>
                       <td>{{$competitor->city->name}}</td>
                       <td>{{$competitor->phone}}</td>
                       <td>{{$competitor->email}}</td>
                       <td>{{$competitor->created_at}}</td>
                       <td>{{$competitor->status}}</td>
                   </tr>
                   @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
    <script>
    $(document).ready(function() {
        $('#example').DataTable( {
            dom: 'Bfrtip',
            buttons: [
                {
                    extend: 'excel',
                    title: 'Reporte de Competidores',            
                }
            ]
        } );
    } );
    </script>
@stop

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>CarsCompany</title>
        <!-- Fonts -->
        <link rel="stylesheet" href="https://unpkg.com/@fortawesome/fontawesome-free@5.14.0/css/all.min.css" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Inter:wght@300;500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      
        <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" crossorigin="anonymous">
        <link href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css" crossorigin="anonymous">
        

        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        @stack('styles')
    </head>
    <body>

        <header>
            <nav class="navbar navbar-expand-lg">
            
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <h2><a class="web-site-title" href="/">CarsCompany</a></h2>
                
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        @if (!Auth::check())
                            <li class="nav-item">
                                <a class="nav-link" href="/login" class="elementor-item">Iniciar Sesión</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/register" class="elementor-item">Registrarse</a>
                            </li>
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="/logout" class="elementor-item">Salir</a>
                            </li>
                        @endif
                    </ul>
                </div>
            </nav>
        </header>

        <main>
            <div id="app">
                @yield('content')
            </div>
        </main>
        @yield('modal')
        @stack('modals')
        
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  

        <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.colVis.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js" crossorigin="anonymous"></script>

<script src="https://cdn.datatables.net/plug-ins/1.10.16/sorting/datetime-moment.js" crossorigin="anonymous"></script>
      
        @yield('scripts')
        @stack('scripts')
    </body>
</html>

resources/views/layouts/flash_messages.blade.php
@if (Session::has('flash_message'))
    <div style="margin:20px auto;" class="alert {{Session::has('flash_alert_type') ? 'alert-'.session('flash_alert_type') : '' }} {{Session::has('flash_message_important') ? 'alert-important' : '' }}">
        @if(Session::has('flash_message_important'))
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @endif
        {{session('flash_message')}}
    </div>
@endif
@if (!empty($errors->all()))
    <div style="margin:20px auto;" class="alert alert-dismissible fade show alert-danger">
       
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
       
        @foreach($errors->all() as $message)
            {{$message}}
        @endforeach
    </div>
@endif